"""Add posted_by column to JobPosting

Revision ID: f185dbe02891
Revises: 
Create Date: 2024-12-06 19:56:03.190787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f185dbe02891'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['posted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('posted_by')

    # ### end Alembic commands ###
